CREATE TABLE `contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractNumber` varchar(50) NOT NULL,
	`versionNumber` decimal(5,1) DEFAULT '1',
	`contractType` enum('سكني','تجاري') DEFAULT 'سكني',
	`status` enum('نشط','منتهي','ملغي','قيد_الانتظار','مراجعة') DEFAULT 'نشط',
	`brokerName` varchar(255),
	`brokerAgreementNumber` varchar(50),
	`createdDate` timestamp,
	`startDate` date,
	`endDate` date,
	`landlordName` varchar(255),
	`landlordIdentity` varchar(20),
	`tenantName` varchar(255),
	`tenantIdentity` varchar(20),
	`deedNumber` varchar(50),
	`propertyId` int,
	`propertyName` varchar(255),
	`propertyType` varchar(100),
	`unitId` int,
	`unitType` varchar(100),
	`unitNumber` varchar(50),
	`city` varchar(100),
	`region` varchar(100),
	`totalContractValue` decimal(15,2) DEFAULT '0',
	`totalDocumentationFees` decimal(15,2) DEFAULT '0',
	`totalDepositAmount` decimal(15,2) DEFAULT '0',
	`brokerageFees` decimal(15,2) DEFAULT '0',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contracts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employees` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`totalCommercialContracts` int DEFAULT 0,
	`totalResidentialContracts` int DEFAULT 0,
	`totalRegisteredContracts` int DEFAULT 0,
	`totalPendingContracts` int DEFAULT 0,
	`totalReviewedContracts` int DEFAULT 0,
	`totalDocumentationFees` decimal(15,2) DEFAULT '0',
	`totalBrokerageFees` decimal(15,2) DEFAULT '0',
	`totalContractAmounts` decimal(15,2) DEFAULT '0',
	`totalRegions` int DEFAULT 0,
	`totalCities` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employees_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `financial_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractId` int,
	`contractNumber` varchar(50),
	`versionNumber` decimal(5,1),
	`tenantIdentity` varchar(20),
	`tenantName` varchar(255),
	`landlordIdentity` varchar(20),
	`landlordName` varchar(255),
	`contractStartDate` varchar(30),
	`contractEndDate` varchar(30),
	`propertyName` varchar(255),
	`invoiceNumber` varchar(50),
	`invoiceDueDate` varchar(30),
	`invoiceIssueDate` varchar(30),
	`invoiceLastDueDate` varchar(30),
	`invoiceStatus` varchar(50),
	`invoiceStatusDescription` varchar(100),
	`totalAmount` decimal(15,2) DEFAULT '0',
	`paidAmount` decimal(15,2) DEFAULT '0',
	`remainingAmount` decimal(15,2) DEFAULT '0',
	`installmentNumber` varchar(50),
	`installmentValue` decimal(15,2),
	`installmentStatus` varchar(50),
	`installmentPaidAmount` decimal(15,2),
	`installmentRemainingAmount` decimal(15,2),
	`installmentDueDate` varchar(30),
	`installmentLastDueDate` varchar(30),
	`paymentMethod` varchar(100),
	`paymentStatus` varchar(50),
	`paymentNumber` varchar(50),
	`paymentAmount` decimal(15,2),
	`paymentDate` varchar(30),
	`receiptMethod` varchar(100),
	`toIban` varchar(50),
	`accountName` varchar(255),
	`transferStatus` varchar(50),
	`referenceNumber` varchar(100),
	`utiNumber` varchar(100),
	`transferDate` varchar(30),
	`bankName` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestNumber` varchar(50),
	`propertyId` int,
	`propertyName` varchar(255),
	`unitId` int,
	`unitNumber` varchar(50),
	`contractId` int,
	`tenantName` varchar(255),
	`tenantPhone` varchar(20),
	`category` enum('كهرباء','سباكة','تكييف','نجارة','دهان','نظافة','أمن','أخرى') DEFAULT 'أخرى',
	`title` varchar(255) NOT NULL,
	`description` text,
	`priority` enum('عاجل','عالي','متوسط','منخفض') DEFAULT 'متوسط',
	`status` enum('جديد','قيد_المعالجة','منتظر_الموافقة','مكتمل','ملغي') DEFAULT 'جديد',
	`assignedTo` varchar(255),
	`estimatedCost` decimal(15,2),
	`actualCost` decimal(15,2),
	`requestDate` timestamp DEFAULT (now()),
	`completionDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenance_requests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `owners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`identityNumber` varchar(20),
	`phone` varchar(20),
	`email` varchar(320),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `owners_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`deedNumber` varchar(50),
	`deedType` varchar(100),
	`ownerId` int,
	`ownerIdentity` varchar(20),
	`ownerName` varchar(255),
	`propertyType` enum('فيلا','شقة','عمارة','مكتب','محل','مستودع','أرض','أخرى') DEFAULT 'أخرى',
	`propertyUsage` varchar(100),
	`city` varchar(100),
	`region` varchar(100),
	`address` text,
	`totalUnits` int DEFAULT 0,
	`totalContracts` int DEFAULT 0,
	`reservedUnits` int DEFAULT 0,
	`rentedUnits` int DEFAULT 0,
	`availableUnits` int DEFAULT 0,
	`totalContractAmount` decimal(15,2) DEFAULT '0',
	`totalDocumentationFees` decimal(15,2) DEFAULT '0',
	`totalBrokerageFees` decimal(15,2) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `properties_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `units` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int,
	`propertyName` varchar(255),
	`unitNumber` varchar(50),
	`unitType` enum('شقة','فيلا','استوديو','غرفة','مكتب','محل','مستودع','أخرى') DEFAULT 'شقة',
	`floor` varchar(20),
	`area` decimal(10,2),
	`rooms` int,
	`bathrooms` int,
	`status` enum('متاحة','مؤجرة','محجوزة','تحت_الصيانة') DEFAULT 'متاحة',
	`rentPrice` decimal(15,2),
	`city` varchar(100),
	`region` varchar(100),
	`deedNumber` varchar(50),
	`ownerName` varchar(255),
	`ownerIdentity` varchar(20),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `units_id` PRIMARY KEY(`id`)
);
